-- CreateTable
CREATE TABLE "Theater" (
    "id" SERIAL NOT NULL,
    "auto_number" INTEGER NOT NULL,
    "name" TEXT NOT NULL,
    "region_cnc" INTEGER NOT NULL,
    "region" TEXT NOT NULL,
    "address" TEXT NOT NULL,
    "insee_code" TEXT NOT NULL,
    "city" TEXT NOT NULL,
    "population" INTEGER NOT NULL,
    "dep" INTEGER NOT NULL,
    "uu" INTEGER NOT NULL,
    "uu_name" TEXT NOT NULL,
    "uu_population" INTEGER NOT NULL,
    "geographic_situation" TEXT NOT NULL,
    "screens" INTEGER NOT NULL,
    "seats" INTEGER NOT NULL,
    "weeks_of_activity" INTEGER NOT NULL,
    "seances" INTEGER NOT NULL,
    "entries_2024" INTEGER NOT NULL,
    "entries_2023" INTEGER NOT NULL,
    "entries_evolution" INTEGER NOT NULL,
    "entries_tranche" TEXT NOT NULL,
    "owner" TEXT NOT NULL,
    "ae" TEXT NOT NULL,
    "ae_category" TEXT NOT NULL,
    "ae_label" TEXT NOT NULL,
    "gender" TEXT NOT NULL,
    "multiplex" TEXT NOT NULL,
    "community_zone" TEXT NOT NULL,
    "number_of_films_programmed" INTEGER NOT NULL,
    "number_of_new_films" INTEGER NOT NULL,
    "number_of_films_in_week1" INTEGER NOT NULL,
    "pd_m_en_entries_french_films" INTEGER NOT NULL,
    "pd_m_entries_american_films" INTEGER NOT NULL,
    "pd_m_entries_european_films" INTEGER NOT NULL,
    "pd_m_entries_other_films" INTEGER NOT NULL,
    "ae_films" INTEGER NOT NULL,
    "ae_part_of_seances" INTEGER NOT NULL,
    "ae_pd_m_entries" INTEGER NOT NULL,
    "latitude" DOUBLE PRECISION NOT NULL,
    "longitude" DOUBLE PRECISION NOT NULL,

    CONSTRAINT "Theater_pkey" PRIMARY KEY ("id")
);

-- CreateIndex
CREATE UNIQUE INDEX "Theater_auto_number_key" ON "Theater"("auto_number");
