/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as VisualizationTheatersRouteImport } from './routes/visualization/theaters'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const VisualizationTheatersRoute = VisualizationTheatersRouteImport.update({
  id: '/visualization/theaters',
  path: '/visualization/theaters',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/visualization/theaters': typeof VisualizationTheatersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/visualization/theaters': typeof VisualizationTheatersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/visualization/theaters': typeof VisualizationTheatersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/visualization/theaters'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/visualization/theaters'
  id: '__root__' | '/' | '/visualization/theaters'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  VisualizationTheatersRoute: typeof VisualizationTheatersRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visualization/theaters': {
      id: '/visualization/theaters'
      path: '/visualization/theaters'
      fullPath: '/visualization/theaters'
      preLoaderRoute: typeof VisualizationTheatersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  VisualizationTheatersRoute: VisualizationTheatersRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
